# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :test do
  scan(package_path: ".", 
    devices: ["iPhone 14", "iPhone 14 Pro"], 
    code_coverage: true,
    scheme: 'HorizontalTileGrid', 
    result_bundle: true)
end

def directory_exists?(directory)
  File.directory?(directory)
end

lane :docbuild do 
  require 'fileutils'
  BASE_DIRECTORY=Pathname.getwd.parent.to_s
  DOCS_FOLDER=BASE_DIRECTORY+"/doc-build-temp"
  FileUtils.remove_dir(DOCS_FOLDER, true)
  puts "Deleting previous dir folder if exists: " + DOCS_FOLDER
  sh('cd ..; xcodebuild docbuild -scheme HorizontalTileGrid -derivedDataPath ' + DOCS_FOLDER + ' -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Plus"')
  PATH_TO_DOARCHIVE_FILE=DOCS_FOLDER+"/Build/Products/Debug-iphonesimulator/HorizontalTileGrid.doccarchive"
  PATH_TO_SAVE_FILES=BASE_DIRECTORY+"/docs"
  FileUtils.remove_dir(PATH_TO_SAVE_FILES, true)
  URL_BASE_PATH="/"
  docc = sh('(xcrun --find docc)')
  sh(docc.strip + ' process-archive transform-for-static-hosting '+PATH_TO_DOARCHIVE_FILE + ' --output-path ' + PATH_TO_SAVE_FILES + ' --hosting-base-path ' + URL_BASE_PATH)
end


