# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :test do
  scan(package_path: ".", 
    devices: ["iPhone 14", "iPhone 14 Pro"], 
    code_coverage: true,
    scheme: 'HorizontalTileGrid', 
    result_bundle: true)
end

lane :docbuild do 
  require 'fileutils'
  
  # PATHs
  BASE_DIRECTORY=Pathname.getwd.parent.to_s
  DOCS_TEMP_FOLDER=BASE_DIRECTORY+"/doc-build-temp"
  PATH_TO_DOARCHIVE_FILE=DOCS_TEMP_FOLDER+"/Build/Products/Debug-iphonesimulator/HorizontalTileGrid.doccarchive"
  PATH_TO_SAVE_FILES=BASE_DIRECTORY+"/docs"
  URL_BASE_PATH="HorizontalTileGrid"

  # Removes the current temp directory if it is exits
  FileUtils.remove_dir(DOCS_TEMP_FOLDER, true)

  # Builds the projects and creates the DocC files in the temp directory
  sh('cd ..; xcodebuild docbuild -scheme HorizontalTileGrid -derivedDataPath ' + DOCS_TEMP_FOLDER + ' -destination "platform=iOS Simulator,OS=16.1,name=iPhone 14 Plus"')
  
  # Removes the old documentations
  FileUtils.remove_dir(PATH_TO_SAVE_FILES, true)

  # Grabs the docc executable
  docc = sh('(xcrun --find docc)')

  # Converts the docC archive to a static website
  sh(docc.strip + ' process-archive transform-for-static-hosting "'+PATH_TO_DOARCHIVE_FILE + '" --hosting-base-path "' + URL_BASE_PATH + '" --output-path "' + PATH_TO_SAVE_FILES + '"')

  # Deletes the temp folder once eveything went well.
  FileUtils.remove_dir(DOCS_TEMP_FOLDER, true)
end

lane :docpush do
  docbuild
  sh('git add .; git commit -m "doc: updates the documentations; git push"')
end